blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/yourusername/arcadia/wiki
    about: Check our documentation for answers to common questions
  - name: Community Discord
    url: https://discord.gg/your-invite-link
    about: Join our Discord server for community support and discussions
  - name: Security Issues
    url: https://github.com/yourusername/arcadia/security/policy
    about: Please report security vulnerabilities through our security policy