/**
 * Centralized icon exports with optimized imports
 *
 * This file provides tree-shakeable icon imports to reduce bundle size.
 * Instead of importing from 'lucide-react' directly, import from this file.
 *
 * Usage:
 * import { HomeIcon, UserIcon } from '@/components/ui/Icons';
 *
 * Note: Only add icons that are actually used in the app.
 * Each icon adds ~1-2KB to the bundle.
 */

// Import all icons as named imports for proper tree-shaking
import {
  Menu,
  X,
  Search,
  Bell,
  Download,
  ChevronDown,
  ChevronRight,
  ChevronLeft,
  ArrowUp,
  ArrowLeft,
  ExternalLink,
  Gamepad2,
  Gamepad,
  Trophy,
  Crown,
  Star,
  Sparkles,
  Zap,
  Puzzle,
  Grid3x3,
  Grid,
  Dice1,
  User,
  Users,
  Users2,
  UserPlus,
  UserMinus,
  UserCircle,
  Settings,
  Lock,
  Key,
  Mail,
  Play,
  Pause,
  RefreshCw,
  RotateCcw,
  Plus,
  PlusCircle,
  Minus,
  Edit,
  Edit3,
  Pencil,
  Trash2,
  Archive,
  GripVertical,
  Check,
  CheckCircle2,
  CheckCircle,
  AlertCircle,
  AlertTriangle,
  Info,
  Loader2,
  Loader,
  WifiOff,
  MessageCircle,
  Calendar,
  Clock,
  Timer,
  Heart,
  ThumbsUp,
  Video,
  VideoOff,
  Volume2,
  Home,
  Activity,
  Package,
  Globe,
  Hash,
  Tags,
  Layers,
  Gauge,
  Wand2,
  Lightbulb,
  Share2,
  MapPin,
  Eye,
  EyeOff,
  Save,
  Copy,
  Package2,
  TrendingUp,
  Shuffle,
} from 'lucide-react';

// Re-export with consistent naming for the app
// Navigation & UI Icons
export {
  Menu as MenuIcon,
  X as XIcon,
  Search as SearchIcon,
  Bell as BellIcon,
  Download as DownloadIcon,
  ChevronDown as ChevronDownIcon,
  ChevronRight as ChevronRightIcon,
  ChevronLeft as ChevronLeftIcon,
  ArrowUp as ArrowUpIcon,
  ArrowLeft as ArrowLeftIcon,
  ExternalLink as ExternalLinkIcon,
};

// Game & Activity Icons
export {
  Gamepad2 as Gamepad2Icon,
  Gamepad as GamepadIcon,
  Trophy as TrophyIcon,
  Crown as CrownIcon,
  Star as StarIcon,
  Sparkles as SparklesIcon,
  Zap as ZapIcon,
  Puzzle as PuzzleIcon,
  Grid3x3 as Grid3x3Icon,
  Grid as GridIcon,
  Dice1 as DiceIcon,
};

// User & Account Icons
export {
  User as UserIcon,
  Users as UsersIcon,
  Users2 as Users2Icon,
  UserPlus as UserPlusIcon,
  UserMinus as UserMinusIcon,
  UserCircle as UserCircleIcon,
  Settings as SettingsIcon,
  Lock as LockIcon,
  Key as KeyIcon,
  Mail as MailIcon,
};

// Action Icons
export {
  Play as PlayIcon,
  Pause as PauseIcon,
  RefreshCw as RefreshCwIcon,
  RotateCcw as RotateCcwIcon,
  Plus as PlusIcon,
  PlusCircle as PlusCircleIcon,
  Minus as MinusIcon,
  Edit as EditIcon,
  Edit3 as Edit3Icon,
  Pencil as PencilIcon,
  Trash2 as Trash2Icon,
  Archive as ArchiveIcon,
  GripVertical as GripVerticalIcon,
};

// Status & Feedback Icons
export {
  Check as CheckIcon,
  CheckCircle2 as CheckCircle2Icon,
  AlertCircle as AlertCircleIcon,
  AlertTriangle as AlertTriangleIcon,
  Info as InfoIcon,
  Loader2 as Loader2Icon,
  Loader as LoaderIcon,
  WifiOff as WifiOffIcon,
};

// Communication Icons
export {
  MessageCircle as MessageCircleIcon,
  Calendar as CalendarIcon,
  Clock as ClockIcon,
  Timer as TimerIcon,
  Heart as HeartIcon,
  ThumbsUp as ThumbsUpIcon,
};

// Media Icons
export { Video as VideoIcon, VideoOff as VideoOffIcon, Volume2 as Volume2Icon };

// Misc Icons
export {
  Home as HomeIcon,
  Activity as ActivityIcon,
  Package as PackageIcon,
  Globe as GlobeIcon,
  Hash as HashIcon,
  Tags as TagsIcon,
  Layers as LayersIcon,
  Gauge as GaugeIcon,
  Wand2 as Wand2Icon,
  Lightbulb as LightbulbIcon,
  Share2 as Share2Icon,
  MapPin as MapPinIcon,
  Eye as EyeIcon,
  EyeOff as EyeOffIcon,
  Save as SaveIcon,
  Copy as CopyIcon,
  Package2 as Package2Icon,
  TrendingUp as TrendingUpIcon,
  Shuffle as ShuffleIcon,
};

// Also export without "Icon" suffix for convenience
export {
  Menu,
  X,
  Search,
  Bell,
  Download,
  ChevronDown,
  ChevronRight,
  ChevronLeft,
  ArrowUp,
  ArrowLeft,
  ExternalLink,
  Gamepad2,
  Trophy,
  Crown,
  Star,
  Sparkles,
  Zap,
  Puzzle,
  Grid3x3 as Grid3X3,
  Grid,
  User,
  Users,
  Users2,
  UserPlus,
  UserMinus,
  UserCircle,
  Settings,
  Lock,
  Key,
  Mail,
  Play,
  Pause,
  RefreshCw,
  RotateCcw,
  Plus,
  PlusCircle,
  Minus,
  Edit,
  Edit3,
  Pencil,
  Trash2,
  Archive,
  GripVertical,
  Check,
  CheckCircle2,
  AlertCircle,
  AlertTriangle,
  Info,
  Loader2,
  Loader,
  WifiOff,
  MessageCircle,
  Calendar,
  Clock,
  Timer,
  Heart,
  ThumbsUp,
  Video,
  VideoOff,
  Volume2,
  Home,
  Activity,
  Package,
  Globe,
  Hash,
  Tags,
  Layers,
  Gauge,
  Wand2,
  Lightbulb,
  Share2,
  MapPin,
  Eye,
  EyeOff,
  Save,
  Copy,
  Package2,
  TrendingUp,
  Shuffle,
  CheckCircle,
};
